### ISSUE TITLE
[Installation Issue] unsafe-perm in lifecycle false Issue

### ISSUE THREAD

**Issue by jopemachine** [jopemachine/alfred-evernote-workflow#42]
## Issue

```
....
7102 silly postinstall glob@7.1.6
7103 info lifecycle glob@7.1.6~postinstall: glob@7.1.6
7104 silly postinstall globby@5.0.0
7105 info lifecycle globby@5.0.0~postinstall: globby@5.0.0
7106 silly postinstall rimraf@2.7.1
7107 info lifecycle rimraf@2.7.1~postinstall: rimraf@2.7.1
7108 silly postinstall del@2.2.2
7109 info lifecycle del@2.2.2~postinstall: del@2.2.2
7110 silly postinstall pump@3.0.0
7111 info lifecycle pump@3.0.0~postinstall: pump@3.0.0
7112 silly postinstall get-stream@5.1.0
7113 info lifecycle get-stream@5.1.0~postinstall: get-stream@5.1.0
7114 silly postinstall cacheable-request@6.1.0
7115 info lifecycle cacheable-request@6.1.0~postinstall: cacheable-request@6.1.0
7116 silly postinstall get-stream@4.1.0
7117 info lifecycle get-stream@4.1.0~postinstall: get-stream@4.1.0
7118 silly postinstall execa@1.0.0
7119 info lifecycle execa@1.0.0~postinstall: execa@1.0.0
7120 silly postinstall get-stream@5.1.0
7121 info lifecycle get-stream@5.1.0~postinstall: get-stream@5.1.0
7122 silly postinstall execa@2.1.0
7123 info lifecycle execa@2.1.0~postinstall: execa@2.1.0
7124 silly postinstall get-stream@4.1.0
7125 info lifecycle get-stream@4.1.0~postinstall: get-stream@4.1.0
7126 silly postinstall got@9.6.0
7127 info lifecycle got@9.6.0~postinstall: got@9.6.0
7128 silly postinstall get-stream@5.1.0
7129 info lifecycle get-stream@5.1.0~postinstall: get-stream@5.1.0
7130 silly postinstall execa@4.0.3
7131 info lifecycle execa@4.0.3~postinstall: execa@4.0.3
7132 silly postinstall write-file-atomic@2.4.3
7133 info lifecycle write-file-atomic@2.4.3~postinstall: write-file-atomic@2.4.3
7134 silly postinstall conf@1.4.0
7135 info lifecycle conf@1.4.0~postinstall: conf@1.4.0
7136 silly postinstall cache-conf@0.6.0
7137 info lifecycle cache-conf@0.6.0~postinstall: cache-conf@0.6.0
7138 silly postinstall xmlbuilder@8.2.2
7139 info lifecycle xmlbuilder@8.2.2~postinstall: xmlbuilder@8.2.2
7140 silly postinstall xmldom@0.1.31
7141 info lifecycle xmldom@0.1.31~postinstall: xmldom@0.1.31
7142 silly postinstall plist@2.1.0
7143 info lifecycle plist@2.1.0~postinstall: plist@2.1.0
7144 silly postinstall alfred-link@0.3.1
7145 info lifecycle alfred-link@0.3.1~postinstall: alfred-link@0.3.1
7146 silly postinstall yallist@2.1.2
7147 info lifecycle yallist@2.1.2~postinstall: yallist@2.1.2
7148 silly postinstall lru-cache@4.1.5
7149 info lifecycle lru-cache@4.1.5~postinstall: lru-cache@4.1.5
7150 silly postinstall cross-spawn@5.1.0
7151 info lifecycle cross-spawn@5.1.0~postinstall: cross-spawn@5.1.0
7152 silly postinstall execa@0.8.0
7153 info lifecycle execa@0.8.0~postinstall: execa@0.8.0
7154 silly postinstall alfred-notifier@0.2.3
7155 info lifecycle alfred-notifier@0.2.3~postinstall: alfred-notifier@0.2.3
7156 silly postinstall @jxa/global-type@1.3.1
7157 info lifecycle @jxa/global-type@1.3.1~postinstall: @jxa/global-type@1.3.1
7158 silly postinstall @jxa/run@1.3.2
7159 info lifecycle @jxa/run@1.3.2~postinstall: @jxa/run@1.3.2
7160 silly postinstall alfy@0.9.1
7161 info lifecycle alfy@0.9.1~postinstall: alfy@0.9.1
7162 silly postinstall clipboardy@2.3.0
7163 info lifecycle clipboardy@2.3.0~postinstall: clipboardy@2.3.0
7164 silly postinstall evernote@2.0.5
7165 info lifecycle evernote@2.0.5~postinstall: evernote@2.0.5
7166 silly postinstall lodash@4.17.19
7167 info lifecycle lodash@4.17.19~postinstall: lodash@4.17.19
7168 silly postinstall os-locale@5.0.0
7169 info lifecycle os-locale@5.0.0~postinstall: os-locale@5.0.0
7170 silly postinstall alfred-evernote-workflow@0.6.5
7171 info lifecycle alfred-evernote-workflow@0.6.5~postinstall: alfred-evernote-workflow@0.6.5
7172 verbose lifecycle alfred-evernote-workflow@0.6.5~postinstall: unsafe-perm in lifecycle false
7173 verbose lifecycle alfred-evernote-workflow@0.6.5~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/alfred-evernote-workflow/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
7174 verbose lifecycle alfred-evernote-workflow@0.6.5~postinstall: CWD: /usr/local/lib/node_modules/alfred-evernote-workflow
7175 silly lifecycle alfred-evernote-workflow@0.6.5~postinstall: Args: [
7175 silly lifecycle   '-c',
7175 silly lifecycle   'alfy-init && npm run initSettingFile && node printPostInstall.js'
7175 silly lifecycle ]
7176 silly lifecycle alfred-evernote-workflow@0.6.5~postinstall: Returned: code: 1  signal: null
7177 info lifecycle alfred-evernote-workflow@0.6.5~postinstall: Failed to exec postinstall script
7178 timing action:postinstall Completed in 1404ms
7179 verbose unlock done using /Users/hjm79/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
7180 timing stage:rollbackFailedOptional Completed in 193ms
7181 timing stage:runTopLevelLifecycles Completed in 14036ms
7182 verbose stack Error: alfred-evernote-workflow@0.6.5 postinstall: `alfy-init && npm run initSettingFile && node printPostInstall.js`
7182 verbose stack Exit status 1
7182 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
7182 verbose stack     at EventEmitter.emit (events.js:315:20)
7182 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
7182 verbose stack     at ChildProcess.emit (events.js:315:20)
7182 verbose stack     at maybeClose (internal/child_process.js:1021:16)
7182 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
7183 verbose pkgid alfred-evernote-workflow@0.6.5
7184 verbose cwd /Users/hjm79
7185 verbose Darwin 19.6.0
7186 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "alfred-evernote-workflow"
7187 verbose node v12.18.3
7188 verbose npm  v6.14.6
7189 error code ELIFECYCLE
7190 error errno 1
7191 error alfred-evernote-workflow@0.6.5 postinstall: `alfy-init && npm run initSettingFile && node printPostInstall.js`
7191 error Exit status 1
7192 error Failed at the alfred-evernote-workflow@0.6.5 postinstall script.
7192 error This is probably not a problem with npm. There is likely additional logging output above.
7193 verbose exit [ 1, true ]

```

**Comment by jopemachine** [comment]
## Related Issues

1. https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/
2. https://github.com/vercel/vercel/issues/677

**Comment by jopemachine** [comment]
## Possible Solutions

1. Install by unsafe-perm flag

```
sudo npm install -g alfred-evernote-workflow --unsafe-perm
```

2. Set unsafe-perm flag to false

```
npm config set unsafe-perm false && npm i -g alfred-evernote-workflow
```
